### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by markoheijnen** [markoheijnen/Minit-Pro#1]

**Comment by szepeviktor** [comment]
https://github.com/kasparsd/minit/issues/53#issuecomment-168699787

**Comment by markoheijnen** [comment]
Not fixed yet. Seeing "Notice: Undefined offset: ...". Also not the whole file looks minified.

**Comment by markoheijnen** [comment]
Broken for background with data entry and for filter:progid:DXImageTransform.Microsoft.gradient

**Comment by szepeviktor** [comment]
Report it https://github.com/ianbogda/CSSqueeze/issues or fix it?

**Comment by markoheijnen** [comment]
I'm trying to fix it and send PR but first need to study the code :laughing:

**Comment by szepeviktor** [comment]
Looks like nice PSR-2 code, you don't have to keep your :eyes: shut.

**Comment by szepeviktor** [comment]
Have you ran https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/blob/master/tests/run.php ?

**Comment by markoheijnen** [comment]
No, any reason why I would do that? ;)

**Comment by szepeviktor** [comment]
OK, I've just ran it and it is OK on its own tests and generates a little bit more code than Java YUI.
It is acceptable.

**Comment by szepeviktor** [comment]
See here https://htmlpreview.github.io/?https://gist.githubusercontent.com/szepeviktor/bc938f57babbb8118318/raw/bd67a2298ad392873ffaa713f100a1c431acb292/YUI-CSS-compressor-PHP-port.html

**Comment by markoheijnen** [comment]
Looks good. Just wanted to have something so I could continue playing with something else.
