### ISSUE TITLE
Minify CSS/JS files for HTTP/2

### ISSUE THREAD

**Issue by markoheijnen** [markoheijnen/Minit-Pro#3]
Since we don't concatenate the files maybe we should use minify them and store that.

**Comment by szepeviktor** [comment]
Please consider server push.
https://nghttp2.org/blog/2015/02/10/nghttp2-dot-org-enabled-http2-server-push/

**Comment by markoheijnen** [comment]
I do. Probably I will implement it when nginx is that far. Before that, it doesn't make much sense.

**Comment by szepeviktor** [comment]
I have a theoretical problem with server push. How do you determine whether the client has already cached the resource in question? ([Apache](https://httpd.apache.org/docs/2.4/mod/mod_http2.html), h2o and nghttp2 already support it.)

**Comment by markoheijnen** [comment]
As far as I know is that you always need to send the headers and that the browser will do what it needs to do. But I haven't played with it since I don't have any benefit of it. Yet.

**Comment by szepeviktor** [comment]
:smile: If the webserver **pushes** a resource the browser has no chance to deny it.

**Comment by szepeviktor** [comment]
See h2o's solution: https://h2o.examp1e.net/configure/http2_directives.html#http2-casper (found on Google)

**Comment by markoheijnen** [comment]
Future problems ;)

**Comment by markoheijnen** [comment]
Marked it as fixed with this nice piece of code :laughing:
